[package]
name = "redis-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
log = { version = "0.4.22", features = [] }
env_logger = "0.11.5"

[dev-dependencies]
stringreader = "0.1.1"
